'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

// Generated by CoffeeScript 2.0.0-beta2
var createAction, createActions, dd, echo, reduxActions;

reduxActions = require('redux-actions');

var _reduxActions = reduxActions;
createAction = _reduxActions.createAction;


dd = require('ddeyes');

echo = console.log;

createActions = function createActions(config) {
  var actionMap, identityActions, k, v;
  actionMap = {};
  identityActions = [];
  for (k in config) {
    v = config[k];
    if (typeof v === 'string') {
      identityActions.push(v);
    } else {
      actions[k] = v;
    }
  }
  return reduxActions.createActions.apply(this, [actionMap].concat(_toConsumableArray(identityActions)));
};

exports.default = { reduxActions: reduxActions, createActions: createActions };

